name: an_state
description: "A reactive state management library for Flutter, providing seamless integration between ViewModels, Widgets, and reactive observables."
version: 1.0.0
homepage: https://github.com/aymtools/an_state/
issue_tracker: https://github.com/aymtools/an_state/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  an_reactive_state: ^1.1.0
  an_async_data: ^1.1.0
  cancellable: ^2.7.0
  anlifecycle: ^3.7.0
  an_lifecycle_cancellable: ^2.6.1
  an_viewmodel: ^3.8.0
  remember: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:

